### ISSUE TITLE
RegTAP bibtex record outdated

### ISSUE THREAD

**Issue by BaptisteCecconi** [ivoa-std/ivoatex#25]
The `std:RegTAP` entry in [ivoabib.bib](https://github.com/ivoa-std/ivoatex/blob/48a0391f63bc9faf50d92f55c5c6879b5355c1b9/ivoabib.bib#L617) is referring to an old WD version, not to the current REC 1.1.

**Comment by msdemlei** [comment]
On Mon, Nov 09, 2020 at 08:11:12AM -0800, Baptiste Cecconi wrote:
> The `std:RegTAP` entry in [ivoabib.bib](https://github.com/ivoa-std/ivoatex/blob/48a0391f63bc9faf50d92f55c5c6879b5355c1b9/ivoabib.bib#L617) is referring to an old WD version, not to the current REC 1.1. 

Do not use bibtex records for standards from ivoabib.bib any more.
All "endorsed" material (RECs, ENs) and the notes that Exec thinks
ought to be referenced must be taken from docrepo.bib exclusively.

These records are still in ivoabib.bib because I didn't want to break
document relying on them.  On the other hand, perhaps it's time to
drop them, if only because when such a document gets touched and
updated, it should reference current versions anyway?

**Comment by BaptisteCecconi** [comment]
ok, sorry. I was confused by the fact that the reference to RegTAP 1.1 (`2019ivoa.spec.1011D`) in the VOEvent document was not resolved by `bibtex`. I added that reference manually (from ADS) in `localrefs.bib`, and it is now displaying correctly the reference.

By the way: I agree with the last paragraph 👍

**Comment by msdemlei** [comment]
Fixed (in some sense of the word) in PR #26
