### ISSUE TITLE
Endorsed Notes don't get the correct top-left banner

### ISSUE THREAD

**Issue by BaptisteCecconi** [ivoa-std/ivoatex#58]
The part of the `ivoatex` script which produces the `html` version of the document is not setting up the correct up-left-side banner for an _IVOA Endorsed Note_, it actually selects the _IVOA Note_ banner. 

You can check this in the fresh EN-UCDList-v1.4: https://ivoa.net/documents/UCD1+/20210616/EN-UCDlist-1.4-20210616.html 
(whereas the main EN page for the document has the correct banner: https://ivoa.net/documents/UCD1+/20210616/index.html)

This issue doesn't seem to be new, since it is also there for the other Endorsed Notes
- https://ivoa.net/documents/Notes/XMLVers/20180529/
- https://ivoa.net/documents/udf-catalogue/20210310/EN-udf-catalogue-1.0-20210310.html
- https://ivoa.net/documents/uat-as-upstream/20201117/PEN-uat-as-upstream-1.0-20201117.html

**Comment by msdemlei** [comment]
On Fri, Jun 25, 2021 at 08:09:10AM -0700, Baptiste Cecconi wrote:
> The part of the `ivoatex` script which produces the `html` version
> of the document is not setting up the correct up-left-side banner
> for an _IVOA Endorsed Note_, it actually selects the _IVOA Note_
> banner. 
> You can check this in the fresh EN-UCDList-v1.4: https://ivoa.net/documents/UCD1+/20210616/EN-UCDlist-1.4-20210616.html 
> (whereas the main EN page for the document has the correct banner: https://ivoa.net/documents/UCD1+/20210616/index.html)

Interesting.  Technically, this backdrop comes in through an
ivoa-side CSS; which of them is used is computed in tth-ivoa.xsl, the
selectDoctypeStyle template.  Since April 29, that has the (then new)
ivoa_pen.css style, so this should be fixed.

Could you try running ``make update`` (which pulls in the most recent
ivoatex, or so I hope) and then a ``make UCDlist.html``?  This should
fix your local copy.

I've added a "run make update" to the ivoatex submission procedure to
help avoid this kind of thing in the future.

> This issue doesn't seem to be new, since it is also there for the
> other Endorsed Notes

I'll ask Giulia to update the CSS references for the existing
documents, so I'd say you can close this bug if the above fixes
things for you.

**Comment by BaptisteCecconi** [comment]
> `make update`

was the solution. Thanks
