### ISSUE TITLE
Issue with HTML output for UCDList

### ISSUE THREAD

**Issue by BaptisteCecconi** [ivoa-std/ivoatex#59]
The HTML output of UCDList has an unexpected output at line 249 of [current HTML version](https://www.ivoa.net/documents/UCD1+/20210616/EN-UCDlist-1.4-20210616.html): 

> `<ol type="a">[label*=*.]`

The string __[label*=*.]__ shows up in the HTML output.

**Comment by BaptisteCecconi** [comment]
NB: the issue is still present after `make update`

**Comment by msdemlei** [comment]
On Mon, Jun 28, 2021 at 04:50:14AM -0700, Baptiste Cecconi wrote:
> The HTML output of UCDList has an unexpected output at line 249 of [current HTML version](https://www.ivoa.net/documents/UCD1+/20210616/EN-UCDlist-1.4-20210616.html): 
> 
> > `<ol type="a">[label*=*.]`

tth, which is what translates ivoatex to HTML, does not actually
process style files ("packages"); hence, you cannot in general say
\usepackage and expect it to work in the HTML output -- and that is
why ivoatexDoc goes to some length trying to explain what to use for
what.

Here, the problem is the enumitem package, which is what gives the
extra options on the enumerate environment.

So... can I move you to remove the option from

```
	\begin{enumerate}[label*=\arabic*.]
```

?  That'll fix the HTML build, although at the cost of having (a),
(b), (c) instead of the sub-enumeration.

Which I'd consider fine -- if you don't I'll hack you something
equivalent not requiring me to teach enumitem to tth.

**Comment by BaptisteCecconi** [comment]
ok, this is what I did to fix this. Thanks.
