### ISSUE TITLE
Accented characters for authors and editors not rendered properly in html.

### ISSUE THREAD

**Issue by tomdonaldson** [ivoa-std/ivoatex#65]
When LaTeX escapes (such as `\'{e}` for an acute-accented `é`) are used in author or editor values, the characters are not rendered correctly in the resulting html.  

Accented characters in the abstract or generic sections seem to be rendered correctly in the html.  Rendering in output pdf appears correct regardless of where the characters are in the document.  UTF-8 characters in the source code appear to render correctly in all versions, but I don't know if that is dependent on local versions of LaTeX.

One can observe these behaviors in the html and pdf files generated from this basic example:
```
\documentclass[11pt,a4paper]{ivoa}
\input tthdefs

\title{Dessert Choice}
\ivoagroup{Applications}

\author{Crème Brûlée}
\author{Cr\`{e}me Br\^{u}l\'{e}e}

\editor{Schwarzwälder Kirschtorte}
\editor{Schwarzw\"{a}lder Kirschtorte}

\begin{document}
\begin{abstract}
La crème brûlée ou Schwarzwälder Kirschtorte?

La cr\`{e}me br\^{u}l\'{e}e ou Schwarzw\"{a}lder Kirschtorte?
\end{abstract}

\section{Introduction}
Préférez-vous la crème brûlée ou Schwarzwälder Kirschtorte?

Pr\'{e}f\'{e}rez-vous la cr\`{e}me br\^{u}l\'{e}e ou Schwarzw\"{a}lder Kirschtorte?
\end{document}
```

**Comment by msdemlei** [comment]
On Tue, Nov 02, 2021 at 11:45:45AM -0700, Tom wrote:
> When LaTeX escapes (such as `\'{e}` for an acute accented `é`) are
> used in author or editor values, the characters are not rendered
> correctly in the resulting html.  

Thanks for building the minimal working example, which, on reading
it, made me wish the pandemic was finally over so we can have
meetings in Strasbourg again.

I tried reproducing it and could not.  However, when trying it in the
document where that failed, ivoa-std/MOC, I could.

It took me a while to spot what's wrong: that document's repo
contains a tthdefs.tex of its own, and that has:

```
{\begin{html}<li class="author">#2</li>\end{html}}
```

in the definition of the author macro rather than

```
{\begin{html}<li class="author">\end{html}#2\begin{html}</li>\end{html}}
```

(note that the HTML environment gets closed before putting in the
macro parameter in the correct version).  In your local version,
tth's TeX engine never gets to see the argument and hence never
expands it.

So, to fix it, just remove tthdefs.tex from the MOC repo; it looks as
if for some reason it has been copied from a very old version of
ivoatex, and the build seems unaffected. 

Anyway, I'll close this bug as "already fixed".
