### ISSUE TITLE
\ivoaBaseURL not applicable to UCDList document  

### ISSUE THREAD

**Issue by BaptisteCecconi** [ivoa-std/ivoatex#84]
The `\ivoaBaseURL` command works well in the general case, when the IVOA document repository URL uses the same name as the `$DOCNAME`. For some reason (historical, I guess), this is not the case for the latest UCD documents, which is not available at: 
- https://www.ivoa.net/documents/UCDlist/20210616/EN-UCDlist-1.4-20210616.html
but at:
- https://www.ivoa.net/documents/UCD1+/20210616/EN-UCDlist-1.4-20210616.html

As a consequence, the previous version links, and the `\auxiliaryurl` commands are not setting up the correct URLs. 

I have setup a dirty fix in the latest UCDlist document:
```
\renewcommand{\ivoaBaseURL}{https://www.ivoa.net/documents/UCD1+}
\renewcommand\currentDocURL % 
	{\ivoaBaseURL/\ivoaDocdatecode}
\renewcommand\currentDocRef % formatted reference to this document's landing page
	{\href{\currentDocURL}{\currentDocURL}}
\renewcommand\latestDocRef 
	% formatted reference to a potential successor to the document's landing page
	{\href{\ivoaBaseURL}{\ivoaBaseURL}}
\renewcommand{\auxiliaryurl}[1]{\href{\currentDocURL/#1}{\currentDocURL/#1}}
```

Any idea to try and do this in a cleaner way ?

**Comment by msdemlei** [comment]
On Fri, Jul 15, 2022 at 10:29:40AM -0700, Baptiste Cecconi wrote:
> Any idea to try and do this in a cleaner way ?  

ivoatex PR #83 <https://github.com/ivoa-std/ivoatex/pull/83> already
does this (or so I hope).  However, you didn't get it because make
update in ivoatex was misguided.  To fix this, in your UCDList
checkout do

  (cd ivoatex && git checkout master)
  git submodule update --remote --rebase

In the future, a simple make update should do the trick again.

With this, you have the lastest ivoatex, where the existing

  DOCREPO_BASEURL=https://ivoa.net/documents/UCD1+

in the Makefile would be enough.

The above incantation would be necessary for all the checkouts involving
ivoatex.  I wonder where I ought to note that...

**Comment by molinaro-m** [comment]
Trying to update ivoatex for the MOC I get this 

```
! LaTeX Error: Command \ivoaBaseURL undefined.
[...]                                                                                             
l.7 \renewcommand{\ivoaBaseURL}
                               {https://www.ivoa.net/documents/moc}
```

am I doing something wrong?

**Comment by msdemlei** [comment]
On Thu, Jul 28, 2022 at 07:22:41AM -0700, Marco Molinaro wrote:
> Trying to update ivoatex for the MOC I get this 
> 
> ```
> ! LaTeX Error: Command \ivoaBaseURL undefined.
> [...]                                                                                             
> l.7 \renewcommand{\ivoaBaseURL}
>                                {https://www.ivoa.net/documents/moc}
> ```
> 
> am I doing something wrong?

Not in inself.  Firstly, this is a consequence of ivoatex having used
git submodules badly.

To recover, can you try the following when in the MOC source directory:

  cd ivoatex
  git checkout master
  git pull
  cd ..

That should get things back in whack, and future make update-s ought
to do the right thing.

Then, in the spirit of having such IVOA-related declarations in the
Makefile (where they don't disturb the document as such) if possible,
it's preferred to say

  DOCREPO_BASEURL=https://www.ivoa.net/documents/moc

in the Makefile rather than do the renewcommand.  There's now
https://github.com/ivoa-std/ivoatexDoc/pull/23 that tries to make
that a bit more discoverable.

**Comment by molinaro-m** [comment]
Ok, it worked! (with an extra make update, actually).
Thanks!
