### ISSUE TITLE
pipe (|) character not well rendered in html conversion

### ISSUE THREAD

**Issue by BaptisteCecconi** [ivoa-std/ivoatex#85]
The pipe character is transformed into `<tt> - </tt>` instead of `<tt> | </tt>` when preparing the html version of a document.

**Comment by msdemlei** [comment]
On Fri, Jul 15, 2022 at 10:41:37AM -0700, Baptiste Cecconi wrote:
> The pipe character is transformed into `<tt> - </tt>` instead of
> `<tt> | </tt>` when preparing the html version of a document. 

Interesting.  That's happening deep in the bowels of tth, and after
aimlessly poking around for a bit I decided to take it to tth's
author.

Meanwhile, \verb.|. will work as expected, and as a general rule I'd
advise to prefer \verb whenever what \texttt is supposed to mean
is something like "input to a computer", if only because computers
tend to want to read funny characters that have a special meaning to
LaTeX, too.

**Comment by msdemlei** [comment]
Ah well.  Live and learn.  It turns out that | usually does an em-dash in LaTeX, except in tt, where, presumably for exactly your use case, it doesn't. What surprised me even more is that plain TeX already behaved like that.

Be that as it may, Ian Hutchinson has kindly fixed tth to emulate LaTeX's behaviour.  I'll push his new version into ivoatex RSN.  That doesn't change my recommendation to use \verb whenever possible.
